export const menuItemsData = [
  {
    id: 1,
    name: 'Quatro queijos',
    info: '',
    price: 44,
    img: '/images/4queijos.png',
  },
  {
    id: 2,
    name: 'Calabresa',
    info: '',
    price: 36,
    img: '/images/calabresa.png',
  },
  {
    id: 3,
    name: 'Frango com catupiry',
    info: '',
    price: 42,
    img: '/images/frangocatu.png',
  },
  {
    id: 4,
    name: 'Banana',
    info: '',
    price: 46,
    img: '/images/banana.png',
  },
  {
    id: 5,
    name: 'Margherita',
    info: '',
    price: 54,
    img: '/images/marguerita.png',
  },
  {
    id: 6,
    name: 'Muçarela',
    info: '',
    price: 64,
    img: '/images/mucarela.png',
  },
  {
    id: 7,
    name: 'Bacon',
    info: '',
    price: 44,
    img: '/images/bacon.png',
  },
  {
    id: 8,
    name: 'Napolitana',
    info: '',
    price: 52,
    img: '/images/napolitana.png',
  },
  {
    id: 9,
    name: 'Chocolate',
    info: '',
    price: 45,
    img: '/images/chocolate.png',
  },
  {
    id: 10,
    name: 'Doce mista',
    info: '',
    price: 64,
    img: '/images/docemista.png',
  },
  {
    id: 11,
    name: 'Doce de leite',
    info: '',
    price: 44,
    img: '/images/doceleite.png',
  },
  {
    id: 12,
    name: 'Portuguesa',
    info: '',
    price: 47,
    img: '/images/portuguesa.png',
  },
  {
    id: 13,
    name: 'Monrango',
    info: '',
    price: 53,
    img: '/images/morango.png',
  },
  {
    id: 14,
    name: 'Romeu e julieta',
    info: '',
    price: 57,
    img: '/images/romeu.png',
  },
  {
    id: 15,
    name: 'Peperoni',
    info: '',
    price: 46,
    img: '/images/peperoni.png',
  },
  {
    id: 16,
    name: 'Chocolate branco',
    info: '',
    price: 42,
    img: '/images/branco.png',
  },
  {
    id: 17,
    name: 'Vegetariana',
    info: '',
    price: 55,
    img: '/images/pizza.png',
  },
  {
    id: 50,
    name: 'Coca-Cola 2L',
    info: '',
    price: 12,
    img: '/images/coca2L.png',
  },
  {
    id: 51,
    name: 'Coca-Cola 600',
    info: '',
    price: 7,
    img: '/images/coca600.png',
  },
  {
    id: 52,
    name: 'Sprite 600',
    info: '',
    price: 7,
    img: '/images/sprite600.png',
  },
  {
    id: 53,
    name: 'Sprite 2L',
    info: '',
    price: 12,
    img: '/images/sprite2L.png',
  },
  {
    id: 54,
    name: 'Guaraná Jesus',
    info: '',
    price: 5,
    img: '/images/guarana_jesus.png',
  },
  {
    id: 55,
    name: 'Guaraná Antartica 2L',
    info: '',
    price: 12,
    img: '/images/guarana2L.png',
  },
];
